import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { type ShoppingItem } from "@prisma/client";
import { useState } from "react";
import { ItemModal } from "~/components/ItemModal";
import { HiX } from "react-icons/hi";

const Home: NextPage = () => {
  const [items, setItems] = useState<ShoppingItem[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const deleteItem = api.items.deleteItem.useMutation();

  //fetch items
  const fetchItems = api.items.queryItems.useQuery(
    {},
    {
      onSuccess: (data) => {
        console.log("success fetching items");
        setItems(data);
      },
    }
  );
  if (fetchItems.status === "loading") {
    return <div>Loading...</div>;
  }

  const handleDeleteItem = (id: string) => {
    deleteItem.mutate(
      { id },
      {
        onSuccess: () => {
          console.log("success deleting item");
          setItems((items) => items.filter((item) => item.id !== id));
        },
      }
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isModalOpen && (
        <ItemModal
          onClose={() => {
            setIsModalOpen(false);
          }}
          setItems={setItems}
        />
      )}
      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My shopping list</h2>
          <button
            type="button"
            className="rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700"
            onClick={() => {
              setIsModalOpen(true);
            }}
          >
            Add shopping item
          </button>
        </div>

        <ul className="mt-4">
          {items.map((item) => (
            <li key={item.id} className="flex justify-between">
              <span>{item.name}</span>
              <HiX
                className={"text-lg text-red-500"}
                onClick={() => handleDeleteItem(item.id)}
              />
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
